[scheduler]
# Number of crawler workers to be used
# This has to be less than Queue Capacity in Local mode (Else Excess will block)
# Increase Worker Pool for Better Speed (NOTE: Very high number will block the crawler)
    workerpool = 20
# Set whether to crawl external domains
    crawlextdomains = false
# Initial Seed Domains
    seedurls = [
    "http://tomblomfield.com"
    ]
[queue]
# Only Local Mode is Supported
# For Remote Mode Implement Queue Interface
   mode = "local"
   [queue.local]
    # Set this to a Substantially large Value Else Crawler Workers will be blocked
        capacity = 100000
        serverport = ""
   [queue.remote]
        capacity = -1
        serverport = ""
[storage]
# Only Local Mode is Supported
# For Remote Mode Implement Storage Interface
   mode = "local"
   [storage.local]
   # map
        serverport = ""
   [storage.redis]
	    serverport = ""
