[scheduler]
# Number of crawler workers to be used
    workerpool = 20
# Set whether to crawl external domains
    crawlextdomains = false
# Initial Seed Domains
    seedurls = [
    "http://tomblomfield.com"
    ]
[queue]
   mode = "local"
   [queue.local]
    # Enable Omit Empty
        capacity = 10000
        serverport = ""
   [queue.remote]
        capacity = -1
        serverport = ""
[storage]
   mode = "local"
   [storage.local]
   # map
        serverport = ""
   [storage.redis]
	    serverport = ""
